#!/bin/bash

sleep 5

export GF_SECURITY_ADMIN_PASSWORD=$(curl -s -k \
									--header "X-Vault-Token:$VAULT_RTOKEN" \
									https://vault:8200/v1/secret/grafana \
									| jq -r .data.GF_SECURITY_ADMIN_PASSWORD)

export GF_SECURITY_ADMIN_USER=$(curl -s -k \
									--header "X-Vault-Token:$VAULT_RTOKEN" \
									https://vault:8200/v1/secret/grafana \
									| jq -r .data.GF_SECURITY_ADMIN_USER)

echo niqueprout ${GF_SECURITY_ADMIN_PASSWORD} $GF_SECURITY_ADMIN_USER
unset VAULT_RTOKEN

exec "$@"