include:
  - ./includes/vault.yml
  - ./includes/metrics_exporters.yml
  - ./includes/volumes.yml
  - ./includes/metrics_monitoring.yml
  - ./includes/networks.yml
  - ./includes/elk.yml

services:

  # ------------------------------ nginx ------------------------------ #

  reverseproxy:
    image: 'owasp/modsecurity:nginx'
    depends_on:
      logstash01:
        condition: service_started
      init_vault:
        condition: service_completed_successfully
    container_name: nginx
    # restart: always
    volumes:
      - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
      - ./nginx/conf/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
      - ./nginx/html:/var/www/html
      - ./nginx/conf/ssl_certificate.sh:/usr/local/bin/ssl_certificate.sh
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # ModSecurity
      - ./security/mod_security/:/etc/modsecurity.d/
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - monitoring
      - auth
    entrypoint: [ "/bin/bash", /usr/local/bin/ssl_certificate.sh ]

  # ------------------------------ micro service ------------------------------ #

  db:
    image: 'postgres:16.6'
    depends_on:
      init_vault:
        condition: service_completed_successfully
    container_name: postgres
    volumes:
      - init_vault:/secret/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=toto_db
      - POSTGRES_USER=toto
      - POSTGRES_PASSWORD=password
    networks:
      - auth
      - monitoring
      - vault

  auth:
    container_name: auth_api
    depends_on:
      logstash01:
        condition: service_started
      db:
        condition: service_started
      init_vault:
        condition: service_completed_successfully
    restart: always
    build: ./backend/auth/
    image: transcendance_auth
    volumes:
      - init_vault:/secret/
    ports:
      - "8000:8000"
    networks:
      - auth
      - monitoring
      - vault
