include:
  - ./includes/vault.yml
  - ./includes/metrics_exporters.yml
  - ./includes/volumes.yml
  - ./includes/metrics_monitoring.yml
  - ./includes/networks.yml
  - ./includes/elk.yml

services:

  # ------------------------------ nginx ------------------------------ #

  reverseproxy:
    image: transcendance_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    # restart: always
    volumes:
      - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
      - ./nginx/conf/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
      - ./nginx/html:/var/www/html
      - ./nginx/conf/ssl_certificate.sh:/usr/local/bin/ssl_certificate.sh
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # ModSecurity
      - ./security/mod_security/:/etc/modsecurity.d/
      - log_nginx:/tmp/log/
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - transcendance

  # ------------------------------ micro service ------------------------------ #

  db:
    image: transcendance_postgres
    build:
      context: ./devops/postgres
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - init_vault:/secret/
      - log_postgres:/tmp/log/
    ports:
      - '5432:5432'
    networks:
      - transcendance

  auth:
    container_name: auth_api
    restart: always
    build: ./backend/auth/
    image: transcendance_auth
    volumes:
      - init_vault:/secret/
    ports:
      - "8000:8000"
    networks:
      - transcendance
