

include: 
 - ./includes/metrics_monitoring.yml
 - ./includes/metrics_exporters.yml
 - ./includes/volumes.yml
 - ./includes/networks.yml
 - ./includes/elk.yml



services:

# ------------------------------ securite ------------------------------ #

  # mod_security:
  #   container_name: mod_security
  #   image: owasp/modsecurity-crs:nginx
  #   ports:
  #     - '8090:80'

# ------------------------------ nginx ------------------------------ #

  reverseproxy:
    image: 'owasp/modsecurity:nginx'
    depends_on: 
      - logstash01
    container_name: nginx
    # restart: always
    volumes:
      - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
      - ./nginx/conf/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
      - ./nginx/html:/var/www/html
      - ./nginx/conf/ssl_certificate.sh:/usr/local/bin/ssl_certificate.sh
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # ModSecurity
      - ./security/mod_security/main.conf:/etc/modsecurity.d/main.conf
      - ./security/mod_security/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - monitoring
      - auth
    entrypoint: ["/bin/bash", /usr/local/bin/ssl_certificate.sh]


# ------------------------------ micro service ------------------------------ #

  db:
    image: 'postgres:16.6'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=toto_db
      - POSTGRES_USER=toto
      - POSTGRES_PASSWORD=password
    networks:
      - auth
      - monitoring

  auth:
    container_name: auth_api
    depends_on:
      - logstash01
    restart: always
    build: ./backend/auth/
    ports:
      - "8000:8000"
    networks:
      - auth
      - monitoring

