version: '3'

services:
  postgres:
    container_name: postgres
    env_file:
      - .postgres.env
    image: postgres:17-bullseye
    ports:
      - 5432:5432

  django:
    depends_on:
      - postgres
    container_name: django
    build:
      context: docker
      dockerfile: ./django/Dockerfile
    ports:
      - 8080:8080
