logging:
  appenders:
    json-layout:
      type: console
      layout:
        type: json
    file:
      type: file
      fileName: /tmp/log/kibana.log
      layout:
        type: json
  root:
    appenders: [file, json-layout]

server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
monitoring.ui.container.elasticsearch.enabled: true
server.name: "kibana"
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key
elasticsearch.hosts: ["https://elastic:9200"]
elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/certs/ca/ca.crt" ]
