# Generated by Django 5.1.4 on 2025-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authconf',
            name='name',
            field=models.CharField(max_length=202),
        ),
        migrations.AlterField(
            model_name='authconf',
            name='password',
            field=models.CharField(max_length=202),
        ),
    ]
