scrape_configs:
  - job_name: nginx
    scrape_interval: 5s
    static_configs:
      - targets:
          - nginx_prometheus_exporter:9113

  - job_name: postgres
    scrape_interval: 5s
    static_configs:
      - targets:
          - postgres_exporter:9187

  - job_name: prometheus
    scheme: https
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: auth
    scrape_interval: 5s
    static_configs:
      - targets:
          - auth:8000

  - job_name: grafana
    scheme: https
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - grafana:3000

  - job_name: logstash
    scrape_interval: 5s
    static_configs:
      - targets:
          - logstash:9198

  - job_name: elastic
    scrape_interval: 5s
    static_configs:
      - targets:
          - elastic:9114

  - job_name: "kibana"
    scrape_interval: 10s
    static_configs:
      - targets:
          - kibana:9684

  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/vault/ca.crt
      insecure_skip_verify: true
    authorization:
      credentials_file: /secret/prometheus_token.txt
    static_configs:
      - targets: ['vault:8200']

rule_files:
  - "/etc/prometheus/alert_rules.yml"
