scrape_configs:
  - job_name: nginx
    scrape_interval: 5s
    static_configs:
    - targets:
      - nginx_prometheus_exporter:9113

  - job_name: postgres
    scrape_interval: 5s
    static_configs:
    - targets:
      - db_exporter:9187

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus:9090

  - job_name: auth
    scrape_interval: 5s
    static_configs:
    - targets:
      - auth:8000

  - job_name: grafana
    scrape_interval: 5s
    static_configs:
    - targets:
      - grafana:3000

  - job_name: logstash
    scrape_interval: 5s
    static_configs:
    - targets:
      - logstash:9187
  