# ------------------------------ monitoring ------------------------------ #
services:
  prometheus:
    container_name: prometheus
    image: transcendance_prometheus
    build:
      context: ../devops/prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheusdata:/data
      - init_vault:/secret/
      - vaultcert:/etc/prometheus/cert/vault
      - log_prometheus:/tmp/log
      - cert_prom:/etc/prometheus/cert/prometheus
      - cert_grafana:/etc/prometheus/cert/grafana
    restart: always
    ports:
      - "9090:9090"
    networks:
      - transcendance

  grafana:
    build:
      context: ../devops/grafana
      dockerfile: Dockerfile
    image: transcendance_grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_LOGS=/tmp/log/
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/cert/grafana/certificate.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/cert/grafana/certificate.key
    volumes:
      - ../devops/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ../devops/grafana/grafana.ini:/etc/grafana/grafana.ini
      - init_vault:/secret/
      - log_grafana:/tmp/log
      - cert_prom:/etc/grafana/cert/prometheus
      - cert_grafana:/etc/grafana/cert/grafana
    networks:
      - transcendance
