# ------------------------------ monitoring ------------------------------ #
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0

    restart: always
    volumes:
      - ../devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    build:
      context: ../devops/grafana
      dockerfile: Dockerfile
    depends_on:
      - vault
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - VAULT_RTOKEN=$VAULT_RTOKEN
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    volumes:
      - ../devops/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ../devops/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring
      - vault
 