services:
  db_exporter:
    container_name: postgres_exporter
    depends_on:
      - db
      - prometheus
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - '9187:9187'
    volumes:
     - init_vault:/secret/
    environment:
      - DATA_SOURCE_URI=db:5432/toto_db?sslmode=disable
      - DATA_SOURCE_USER=toto
      - DATA_SOURCE_PASS=password
    networks:
      - monitoring
      - vault
    command: '--no-collector.stat_bgwriter'

  nginx_prometheus_exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter:1.4.0
    depends_on:
      - prometheus
      - reverseproxy
    ports:
      - '9113:9113'
    networks:
      - monitoring
    command:
      - --nginx.scrape-uri=https://nginx/status
