services:
  postgres_exporter:
    restart: always
    container_name: postgres_exporter
    image: transcendance_postgres_exporter
    build:
      context: ../devops/postgres_exporter
      dockerfile: Dockerfile
    volumes:
      - init_vault:/secret/
      - log_postgres_exporter:/tmp/log/
    networks:
      - transcendance

  nginx_prometheus_exporter:
    restart: always
    container_name: nginx_exporter
    image: transcendance_nginx_exporter
    build:
      context: ../devops/nginx_exporter
      dockerfile: Dockerfile
    volumes:
      - log_nginx_exporter:/tmp/log
    networks:
      - transcendance
