services:
# ------------------------------ securite ------------------------------ #
  vault:
    container_name: vault
    image: hashicorp/vault:1.18
    user: 0:0
    env_file:
      - "../security/vault/vault.env"
    ports:
      - "8203:8200"
    networks:
      - vault
    volumes:
      - ../security/vault/entrypoint.sh:/entrypoint.sh
      - ../security/vault/config/config.hcl:/vault/config/config.hcl
      - vaultcert:/vault/tls
      - vaultdata:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
     VAULT_ADDR: "https://127.0.0.1:8200"
    entrypoint: ["/bin/sh", ./entrypoint.sh]
    command: vault server -config /vault/config/config.hcl

  init_vault:
    image: alpine:latest
    container_name: init_vault
    depends_on:
      - vault
    volumes:
      - ../security/vault/init_vault.sh:/init_vault.sh
      - ../security/vault/secrets.json:/secrets.json
      - init_vault:/secret/
    entrypoint: ["/bin/sh", "/init_vault.sh"]
    restart: no
    networks: 
     - vault